name: Windows x64 GN/MSVC (Release)

on:
  # This is a required workflow specified in branch enforcement
  # and must run unconditionally to allow merges.
  push:
  pull_request:

jobs:

  win_msvc_rel_x64:

    runs-on: windows-2019

    steps:
    - name: Git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Install depot_tools
      shell: cmd
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git ..\depot_tools
        set "PATH=%CD%\..\depot_tools;%PATH%"
        gclient

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: actions/checkout@v2
      with:
        path: test
        fetch-depth: 0

    - name: Sync code for main branch (with patch)
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd test
        copy scripts\standalone.gclient .gclient
        gclient sync

    - name: Generate shared library for main branch (with patch)
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd test
        gn gen out\Release --args="is_debug=false is_clang=false gpgmm_shared_library=true"

    - name: Build shared library for main branch (with patch)
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd test
        ninja -C out\Release gpgmm

    - name: Generate project for main branch (with patch)
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd test
        gn gen out\Release --args="is_debug=false is_clang=false gpgmm_force_tracing=true"

    - name: Build for main branch (with patch)
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd test
        ninja -C out\Release

    - name: Run gpgmm_end2end_tests runtime leak checks (with patch)
      shell: cmd
      run: |
        cd test
        out\Release\gpgmm_end2end_tests.exe --no-leaks 2>&1

    - name: Run gpgmm_end2end_tests no leak tests (with patch)
      shell: cmd
      run: |
        cd test
        out\Release\gpgmm_end2end_tests.exe --gtest_filter=*NoLeak --check-device-leaks 2>&1

    - name: Run gpgmm_end2end_tests (with patch)
      shell: cmd
      run: |
        cd test
        out\Release\gpgmm_end2end_tests.exe --gtest_filter=-*NoLeak --check-device-leaks 2>&1

    - name: Run gpgmm_unittests (with patch)
      shell: cmd
      run: |
        cd test
        out\Release\gpgmm_unittests.exe

    - name: Run gpgmm_capture_replay_tests (with patch)
      shell: cmd
      run: |
        cd test
        out\Release\gpgmm_capture_replay_tests.exe --check-device-leaks 2>&1
