name: win_msvc_dbg_x64_cmake

on:
  push:
    paths:
      - 'src/**'

  pull_request:
    paths:
      - 'src/**'

jobs:

  job:

    runs-on: windows-2019

    steps:
    - name: Git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Install vcpkg
      shell: cmd
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat

    - name: Install depot_tools
      shell: cmd
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git ..\depot_tools
        set "PATH=%CD%\..\depot_tools;%PATH%"
        gclient

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: actions/checkout@v2
      with:
        path: test
        fetch-depth: 0

    - name: Sync code for main branch (with patch)
      shell: cmd
      run: |
        set "PATH=%CD%\..\depot_tools;%PATH%"
        set "DEPOT_TOOLS_WIN_TOOLCHAIN=0"
        cd test
        copy scripts\standalone.gclient .gclient
        gclient sync

    - name: Generate project for main branch (with patch)
      shell: cmd
      run: |
        cd test
        cmake . -DCMAKE_BUILD_TYPE=Debug -DGPGMM_ENABLE_VK=OFF -DCMAKE_TOOLCHAIN_FILE=..\vcpkg\scripts\buildsystems\vcpkg.cmake

    - name: Build for main branch (with patch)
      shell: cmd
      run: |
        cd test
        cmake --build .

    - name: Run gpgmm_end2end_tests (with patch)
      shell: cmd
      run: |
        cd test
        src\tests\Debug\gpgmm_end2end_tests.exe 2>&1

    - name: Run gpgmm_unittests (with patch)
      shell: cmd
      run: |
        cd test
        src\tests\Debug\gpgmm_unittests.exe
